version: "3.4"

services:
  postgres:
    container_name: prisma-tutorial
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
      POSTGRES_PASSWORD: todo

volumes:
  postgres_data: